# Pipeline CI/CD principal
name: CI Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Récupération du code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Construction de l'image Docker du Backend
      - name: Build Backend
        run: docker build -t taskboard-backend:latest -f Dockerfile.backend .

      # Construction de l'image Docker du Frontend
      - name: Build Frontend
        run: docker build -t taskboard-frontend:latest -f Dockerfile.frontend .
